echo "Tugas 1 sistem oprasi kelas B"
echo "................................"
echo "nama : ilil musyarof asfiani"
echo "Npm :21083010073"
echo "................................"
echo "Hallo Dunia"
echo "Ini adalah skrip Bash pertamaku di linux"
